name: zooper_flutter_id3
description: A new Flutter package project.
version: 0.0.1-alpha
homepage:

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  convert: 3.0.1

  collection: ^1.15.0

  equatable: ^2.0.0

  file_picker: ^4.3.3

  zooper_flutter_encoding_utf16: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
