name: zooper_flutter_id3
description: The best library written in dart for reading and writing id3 tags
version: 0.0.4-alpha
homepage: https://github.com/zooper-lib/zooper_flutter_id3

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  convert: ^3.0.1

  collection: ^1.15.0

  equatable: ^2.0.0

  file_picker: ^6.1.1

  quiver: ^3.0.1+1

  zooper_flutter_encoding_utf16: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
